name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t jonherman/stravacollection:latest .

    - name: Push the Docker image
      run: docker push jonherman/stravacollection:latest

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 52.91.174.188
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull jonherman/stravacollection:latest
          docker stop stravacollection || true
          docker rm stravacollection || true
          docker run -d --name stravacollection -p 80:8080 jonherman/stravacollection:latest