name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client/web
        push: true
        tags: "jonherman/stravacollection:latest"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 52.91.174.188
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull jonherman/stravacollection:latest
          docker stop stravacollection || true
          docker rm stravacollection || true
          docker run -d --name stravacollection -p 80:8080 jonherman/stravacollection:latest