name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:dind # Docker in Docker
          ports:
            - 2375:2375 # Expose the Docker daemon port (not recommended for production)
          options: --privileged # Necessary for Docker in Docker    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client/web
        push: true
        tags: "jonherman/stravacollection:latest"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 52.91.174.188
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull jonherman/stravacollection:latest
          sudo docker stop stravacollection || true
          sudo docker rm stravacollection || true
          sudo docker run -d --name stravacollection -p 80:3000 jonherman/stravacollection:latest